version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mymongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
    networks:
      - mynet

  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongoexpress
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass123
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - mynet

  nodeapp:
    build: .
    container_name: nodemongoapp
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

